name: PixelEffect
main: net.pixeleffect.PixelEffectPlugin
version: 6.1.1
author: Coco_gigpn, Wytrem
commands:
  pixeleffect:
    description: PixelEffect main command.
    usage: /pixeleffect help
    permission: pixeleffect.use
    aliases:
    - pe
